os:
  - linux
language: cpp
compiler:
  - clang
  - gcc
env:
  - GCC_VERSION=5
  - GCC_VERSION=6
  - GCC_VERSION=7
  - GCC_VERSION=8
matrix:
  exclude:
    - compiler: clang
      env: GCC_VERSION=5
    - compiler: clang
      env: GCC_VERSION=6
    - compiler: clang
      env: GCC_VERSION=7
sudo: false
addons:
  apt:
    sources:
      - george-edison55-precise-backports
      - ubuntu-toolchain-r-test
      - boost-latest
      - llvm-toolchain-trusty-5.0
      - llvm-toolchain-trusty-6.0
      - llvm-toolchain-trusty
    packages:
      - g++-5
      - g++-6
      - g++-7
      - g++-8
      - clang-6.0
      - libgmp-dev
      - libeigen3-dev
      - libboost1.55-dev
install: true
script:
  - ./bin/travisci_build_$TRAVIS_OS_NAME.sh
after_failure:
  - cat include/libint2/config.h
  - cat config.log
  - cat export_build/config.log
  - ls -l export_build
notifications:
  email:
    recipients:
      - libint+travisci@valeyev.net
    on_success: change
    on_failure: always
