os:
  - linux
language: cpp
dist: bionic
env:
  global:
    - BUILD_PREFIX=/home/travis/_build
    - INSTALL_PREFIX=/home/travis/_install
addons:
  apt:
    packages: &base_packages
      - libgmp-dev
      - automake
      - cmake # for eigen
      - libboost-dev

matrix:
  fast_finish: true
  include:
    - compiler: gcc
      env: GCC_VERSION=6 BUILD_TYPE=Debug
      addons:
        apt:
          packages:
            - *base_packages
            - g++-6
            - gfortran-6
    - compiler: gcc
      env: GCC_VERSION=6 BUILD_TYPE=Release
      addons:
        apt:
          packages:
            - *base_packages
            - g++-6
            - gfortran-6
    - compiler: gcc
      env: GCC_VERSION=7 BUILD_TYPE=Debug
      addons:
        apt:
          packages:
            - *base_packages
            - g++-7
            - gfortran-7
    - compiler: gcc
      env: GCC_VERSION=7 BUILD_TYPE=Release
      addons:
        apt:
          packages:
            - *base_packages
            - g++-7
            - gfortran-7
    - compiler: gcc
      env: GCC_VERSION=8 BUILD_TYPE=Debug
      addons:
        apt:
          packages:
            - *base_packages
            - g++-8
            - gfortran-8
    - compiler: gcc
      env: GCC_VERSION=8 BUILD_TYPE=Release
      addons:
        apt:
          packages:
            - *base_packages
            - g++-8
            - gfortran-8
    - compiler: gcc
      env: GCC_VERSION=9 BUILD_TYPE=Debug
      addons:
        apt:
          sources:
            - sourceline: 'ppa:ubuntu-toolchain-r/test'
          packages:
            - *base_packages
            - g++-9
            - gfortran-9
    - compiler: gcc
      env: GCC_VERSION=9 BUILD_TYPE=Release
      addons:
        apt:
          sources:
            - sourceline: 'ppa:ubuntu-toolchain-r/test'
          packages:
            - *base_packages
            - g++-9
            - gfortran-9
    - compiler: clang
      env: CLANG_VERSION=8 GCC_VERSION=8 BUILD_TYPE=Debug
      addons:
        apt:
          packages:
            - *base_packages
            - clang-8
            - libc++-8-dev
            - libc++abi-8-dev
            - gfortran-8
    - compiler: clang
      env: CLANG_VERSION=8 GCC_VERSION=8 BUILD_TYPE=Release
      addons:
        apt:
          packages:
            - *base_packages
            - clang-8
            - libc++-8-dev
            - libc++abi-8-dev
            - gfortran-8
    - compiler: clang
      env: CLANG_VERSION=9 GCC_VERSION=8 BUILD_TYPE=Debug
      addons:
        apt:
          sources:
            - sourceline: 'deb http://apt.llvm.org/bionic/ llvm-toolchain-bionic-9 main'
              key_url: 'https://apt.llvm.org/llvm-snapshot.gpg.key'
          packages:
            - *base_packages
            - g++-8
            - gfortran-8
            - clang-9
            - libc++-9-dev
            - libc++abi-9-dev
    - compiler: clang
      env: CLANG_VERSION=9 GCC_VERSION=8 BUILD_TYPE=Release
      addons:
        apt:
          sources:
            - sourceline: 'deb http://apt.llvm.org/bionic/ llvm-toolchain-bionic-9 main'
              key_url: 'https://apt.llvm.org/llvm-snapshot.gpg.key'
          packages:
            - *base_packages
            - g++-8
            - gfortran-8
            - clang-9
            - libc++-9-dev
            - libc++abi-9-dev

install: true
before_install:
  - env
  - mkdir -p ${BUILD_PREFIX} && mkdir -p ${INSTALL_PREFIX}
script:
  - ./bin/travisci_build_$TRAVIS_OS_NAME.sh
after_failure:
  - cat include/libint2/config.h
  - cat config.log
  - cat export_build/config.log
  - ls -l export_build
notifications:
  email:
    recipients:
      - libint+travisci@valeyev.net
    on_success: change
    on_failure: always
