os:
  - linux
language: cpp
compiler:
  - clang
  - gcc
env:
  - GCC_VERSION=4.9
  - GCC_VERSION=5
  - GCC_VERSION=6
#  - GCC_VERSION=7
matrix:
  exclude:
    - compiler: clang
      env: GCC_VERSION=4.9
    - compiler: clang
      env: GCC_VERSION=5
#    - compiler: clang
#      env: GCC_VERSION=6
sudo: false
addons:
  apt:
    sources:
      - george-edison55-precise-backports
      - ubuntu-toolchain-r-test
      - llvm-toolchain-precise
      - boost-latest
    packages:
      - g++-4.9
      - g++-5
      - g++-6
#      - g++-7
      - gfortran-4.9
      - gfortran-5
      - gfortran-6
#      - gfortran-7
      - clang-5.0
      - libgmp-dev
      - libeigen3-dev
      - libboost1.55-dev
install: true
script:
  - ./bin/travisci_build_$TRAVIS_OS_NAME.sh
after_failure:
  - cat include/libint2/config.h
  - cat config.log
  - cat export_build/config.log
  - ls -l export_build
notifications:
  email:
    recipients:
      - libint+travisci@valeyev.net
    on_success: change
    on_failure: always
