os:
  - linux
language: cpp
compiler:
  - clang
  - gcc
env:
  matrix:
    - GCC_VERSION=5
    - GCC_VERSION=6
    - GCC_VERSION=7
    - GCC_VERSION=8
  global:
    - BUILD_PREFIX=/home/travis/_build
    - INSTALL_PREFIX=/home/travis/_install
matrix:
  exclude:
    - compiler: clang
      env: GCC_VERSION=5
    - compiler: clang
      env: GCC_VERSION=6
    - compiler: clang
      env: GCC_VERSION=7
sudo: false
addons:
  apt:
    sources:
      - ubuntu-toolchain-r-test
      - boost-latest
      - llvm-toolchain-trusty-6.0
    packages:
      - g++-5
      - g++-6
      - g++-7
      - g++-8
      - clang-6.0
      - libgmp-dev
      - libeigen3-dev
      - libboost1.55-dev
install: true
before_install:
  - env
  - mkdir -p ${BUILD_PREFIX} && mkdir -p ${INSTALL_PREFIX}
script:
  - ./bin/travisci_build_$TRAVIS_OS_NAME.sh
after_failure:
  - cat include/libint2/config.h
  - cat config.log
  - cat export_build/config.log
  - ls -l export_build
notifications:
  email:
    recipients:
      - libint+travisci@valeyev.net
    on_success: change
    on_failure: always
